### ISSUE TITLE
3d işlemi

### ISSUE THREAD

**Issue by necoakdogan** [ahmett/payconn-qnbfinansbank#3]
Merhaba, 
verdiğiniz örnek ile direk para çekimi sağlanıyor ancak önce 3d işlemi yapılmasını arzu etmekteyiz. Bunun için nasıl bir yol izlenebilir?

İyi çalışmalar.

**Comment by ahmett** [comment]
Merhaba,

3D Secure yolu ile ödeme almak istiyorsanız **Authorize** ve **Complete** aksiyonlarını sırasıyla gerçekleştirmeniz yeterli olacaktır. Dokümantasyon üzerinde bulunan ilgili kısımları aşağıda sizinle paylaşıyorum.

Authorize: https://payconn.github.io/qnbfinansbank#authorize
Complete: https://payconn.github.io/qnbfinansbank#complete

İyi çalışmalar.

**Comment by necoakdogan** [comment]
İlginiz için minnetarım. İnceleyeceğim. Teşekkür ederim.
